services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  danbooru-worker:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - DANBOORU_LOGIN=${DANBOORU_LOGIN}
      - DANBOORU_API_KEY=${DANBOORU_API_KEY}
      - RATE_LIMIT_PER_MINUTE=60
      - CACHE_TTL_SECONDS=3600
      - DANBOORU_LIMIT=1
      - DANBOORU_RANDOM=true
      - API_SECRET=${API_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
