env_file:
  - .env

services:
  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
      - ./certs/redis:/certs/redis:ro
      - ./secrets/redis_password.txt:/run/secrets/redis_password:ro
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >-
      sh -c "
        redis-server \
          --port 0 \
          --tls-port 6380 \
          --tls-cert-file /certs/redis/redis.crt \
          --tls-key-file /certs/redis/redis.key \
          --tls-ca-cert-file /certs/redis/ca.crt \
          --requirepass ${REDIS_PASSWORD} \
          --appendonly yes \
          --dir /data \
          &
        PID=$$!
        sleep 10
        redis-cli --tls --cacert /certs/redis/ca.crt --cert /certs/redis/redis-client.crt --key /certs/redis/redis-client.key -p 6380 \
          ACL SETUSER default on >${REDIS_PASSWORD} ~* +@all
        wait $$!
      "
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --user default -a ${REDIS_PASSWORD} --tls --cacert /certs/redis/ca.crt --cert /certs/redis/redis-client.crt --key /certs/redis/redis-client.key -h localhost -p 6380 PING"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  danbooru-worker:
    build: .
    command: npm run start:prod
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_USE_TLS=true
      - REDIS_URL=rediss://default:${REDIS_PASSWORD}@redis:6380
      - REDIS_TLS_CA=/app/certs/redis/ca.crt
      - REDIS_TLS_CERT=/app/certs/redis/redis-client.crt
      - REDIS_TLS_KEY=/app/certs/redis/redis-client.key
    volumes:
      - ./certs/redis:/app/certs/redis:ro
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis --user default -a ${REDIS_PASSWORD} --tls --cacert /app/certs/redis/ca.crt --cert /app/certs/redis/redis-client.crt --key /app/certs/redis/redis-client.key -p 6380 ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:

