services:
  redis:
    image: redis:alpine
    command: >
      redis-server
      --tls-port 6379
      --port 0
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
      --tls-cert-file /certs/redis.crt
      --tls-key-file /certs/redis.key
      --tls-ca-cert-file /certs/ca.crt
      --tls-auth-clients yes
    volumes:
      - redis_data:/data
      - ./certs:/certs:ro
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p 6379 --tls --cacert /certs/ca.crt -a $REDIS_PASSWORD ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  danbooru-worker:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_USE_TLS=true
      - REDIS_URL=rediss://${REDIS_PASSWORD}@redis:6379
      - REDIS_TLS_CA=/certs/ca.crt
      - REDIS_TLS_CERT=/certs/redis.crt
      - REDIS_TLS_KEY=/certs/redis.key
      - DANBOORU_LOGIN=${DANBOORU_LOGIN}
      - DANBOORU_API_KEY=${DANBOORU_API_KEY}
      - RATE_LIMIT_PER_MINUTE=60
      - CACHE_TTL_SECONDS=3600
      - DANBOORU_LIMIT=1
      - DANBOORU_RANDOM=true
      - API_SECRET=${API_SECRET}
    volumes:
      - ./certs:/certs:ro
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis -p 6379 --tls --cacert /certs/ca.crt -a $REDIS_PASSWORD ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:

secrets:
  redis_password:
    file: ./secrets/redis_password.txt
